---
variables:
  LATEX_IMAGE: listx/texlive:2020

build:
  image: listx/texlive:2020
  script:
      # see https://stackoverflow.com/a/2461957/1074188
      # this will generate a document with question marks in place of unknown references
      - pdflatex -interaction batchmode main.tex
      # this will parse all the .bib files that were included in the article and generate metainformation regarding references
      - bibtex- main.aux
      # this will generate document with all the references in the correct places
      - pdflatex -interaction batchmode -draftmode main.tex
      # just in case if adding references broke page numbering somewhere
      - pdflatex -interaction batchmode main.tex

  artifacts:
    paths:
      - "*.pdf"
